### ISSUE TITLE
How to implement auto-login after signup?

### ISSUE THREAD

**Issue by ahsang** [trailsjs/sails-permissions#107]
I cannot figure out how to automatically login after a user is signed up.

**Comment by s-devaney** [comment]
+1

**Comment by dottodot** [comment]
I'm looking for the same thing. I was hoping using `req.login` after the user was created would work but I get an error of `[Error: passport.initialize() middleware not in use]`

**Comment by schartz** [comment]
I am also facing the exact same issue. Any workaround would be much appreciated.

**Comment by ahsang** [comment]
@schartz i think this can be figured out somehow. will look at it in a while i am sure we can find a way.

**Comment by anabelle** [comment]
Any progress on this one?
