### ISSUE TITLE
ReferenceError: sails is not defined

### ISSUE THREAD

**Issue by brylie** [trailsjs/sails-permissions#245]
When following the steps in the README, I am having difficulty [setting up local.js](https://github.com/langateam/sails-permissions#eg-in-configlocaljs-file-is-in-gitignore). I am getting errors related to sails not being defined:

```
Details:ReferenceError: sails is not defined
```

and...

```
sails.config.permissions.adminUsername = 'admin',
     ^
SyntaxError: Unexpected token .
```

Where should I put the initial admin configuration object, inside of `module.exports`?

**Comment by nathanBrenner** [comment]
Getting the same error

**Comment by tjwebb** [comment]
What version of sails?
